apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webapp
  template:
    metadata:
      labels:
        app: nginx-webapp
    spec:
      containers:
      - name: nginx-webapp
        image: prasanthrajrp/nginx-webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
